---
version: "3"
services:
  neo-faucet:
    container_name: neo-faucet
    depends_on:
      - neo-scan-api
    environment:
      NEOSCAN: "neo-scan-api:4000"
    image: cityofzion/neo-local-faucet:latest
    links:
      - "neo-scan-api:4000"
    ports:
      - "4002:4002"

  neo-nodes:
    container_name: neo-nodes
    image: txhsl/neo-cli-docker-fulldata:ex90k
    ports:
      - "20333:10001"
      - "20334:20001"
      - "20335:30001"
      - "20336:40001"
      - "30333:10003"
      - "30334:20003"
      - "30335:30003"
      - "30336:40003"

  neo-scan-api:
    container_name: neo-scan-api
    depends_on:
    - postgres
    - neo-nodes
    - notifications-server
    environment:
      HOST: "${HOST_NAME}"
      NEO_NOTIFICATIONS_SERVER: "http://${NOTIFICATIONS_SERVER}:8080/v1"
      NEO_SEEDS: "http://${SEED_SERVER}:10003;http://${SEED_SERVER}:20003;http://${SEED_SERVER}:30003;http://${SEED_SERVER}:40003"
      PORT: 4000
      DB_HOSTNAME: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: neoscan_prodv
      REPLACE_OS_VARS: "true"
    image: registry.gitlab.com/cityofzion/neo-scan/api:latest
    links:
    - "neo-nodes:10003"
    - "neo-nodes:20003"
    - "neo-nodes:30003"
    - "neo-nodes:40003"
    ports:
    - "4000:4000"

  neo-scan-sync:
    container_name: neo-scan-sync
    depends_on:
      - postgres
      - neo-nodes
      - notifications-server
    environment:
      NEO_NOTIFICATIONS_SERVER: "http://${NOTIFICATIONS_SERVER}:8080/v1"
      NEO_SEEDS: "http://${SEED_SERVER}:10003;http://${SEED_SERVER}:20003;http://${SEED_SERVER}:30003;http://${SEED_SERVER}:40003"
      DB_HOSTNAME: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: neoscan_prodv
      REPLACE_OS_VARS: "true"
    image: registry.gitlab.com/cityofzion/neo-scan/sync:latest
    links:
      - "neo-nodes:10003"
      - "neo-nodes:20003"
      - "neo-nodes:30003"
      - "neo-nodes:40003"

  notifications-server:
    command: "/usr/bin/python3 /neo-python/neo/bin/api_server.py --config /neo-python/custom-config.json --port-rest 8080"
    container_name: notifications-server
    depends_on:
      - neo-nodes
    image: cityofzion/neo-python:v0.8.0
    ports:
      - "8080:8080"
    volumes:
      - "./notifications-server.config.json:/neo-python/custom-config.json"

  postgres:
    container_name: postgres
    environment:
      POSTGRES_DB: neoscan_prodv
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    expose:
      - 5432
    image: postgres:10.5
